---
title: "Julia’s Tab 2 Attempt"
author: "Julia Dagum"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Join energy generation plant info with locational plant info. Filtered for Solar PV.

```{r}
# ----------
# Install ibraries
# ---------

library(tidyverse)
library(lubridate)
library(janitor)
library(here)
library(sf)

```

```{r}

# ----------
# Read in data 
# ----------

gen_by_plant <- read_csv(here::here("data", "annual_generation_by_power_plant.csv"))

plant_info <- read_csv(here::here("data", "plant_info.csv"), 
                       skip = 12, col_names = TRUE)

# --------
# Clean up data
# --------

tidy_gen_by_plant <- gen_by_plant %>% 
  clean_names() %>% 
  select(year, state, cec_plant_id, status, start_date, retire_date, prime_mover_id, prime_mover_desc, capacity, gross_m_wh, net_m_wh) %>% 
  rename("gross_mwh" = "gross_m_wh") %>% 
  rename("net_mwh" = "net_m_wh") %>% 
  # filter for just photovoltaics (this excludes solar thermal, wind, etc.)
  # but there are still plants that say the energy source is natural gas/other non-solar...
  filter(prime_mover_id == "PV")
  # for visuals, remember to filter out non-operational systems once they have a "retire date" so they still show up if a year is selected before retirement

tidy_plant_info <- plant_info %>% 
  clean_names() %>% 
  # we'll already have state in the other df
  select(-state)

# --------
# Join dataframes
# ---------

plants_location_join <- inner_join(tidy_plant_info, tidy_gen_by_plant, "cec_plant_id")
# note that there are a 19 entries wiht energy_source_category not equal to "SUN" but prime_mover_id equal to "PV"

```

### Get spatial data

```{r}
# Make California base layer
ca <- read_sf(dsn = here::here("data", "states"),
              layer = "cb_2017_us_state_20m") %>% 
  dplyr::select(NAME) %>% 
  filter(NAME == "California") %>% 
  st_transform(crs = 4326)

# Read in CA counties
ca_counties <- read_sf(dsn = here::here("data", "ca_counties"), 
                       layer = "california_county_shape_file") %>% 
  rename(county = "NAME")

# Join plant information to CA counties and make sf object with sticky geometries
plant_county_join <- full_join(plants_location_join, ca_counties, "county")
plant_county_sf <- st_as_sf(plant_county_join)
# Why does the new file have 5500 observations when it was something that started with 4100 joined to 78?????????????!!!!!!

# -------------------------------------
# I don't actually think it makes sense to join cities from cal enviroscreen:

# Use nearby cities from Cal Enviro-screen data to join with plants
# Read in data set
env_scrn_df <- read_csv(here::here("data", "CalEnviroScreen.csv")) %>% 
  clean_names() %>% 
  rename(nearby_city = nearby_city_to_help_approximate_location_only,
         lon = longitude,
         lat = latitude,
         county = california_county) %>% 
  select(-contains("pctl"), -contains("percentile"))

# Convert to sf
env_scrn_sf <- st_as_sf(env_scrn_df, coords = c("lon", "lat"), crs = 4326) %>% 
  rename(city = "nearby_city")

# Try joining plant cities with cal enviro-screen nearby cities
plant_city_join <- full_join(plants_location_join, env_scrn_sf, "city")

```

### Make map with solar plants by county
*Not sure if this is the right number because some of the plants have prime_mover_id as photovotaic but then the energy_source_category column is not solar...
```{r}
# Does it make sense to use st_intersection (from session 3 video)??
# Not sure what that would do

# Instead just use plant_county_sf

plants_per_county <- plant_county_sf %>% 
  group_by(county) %>% 
  tally()
# tally counts number of plants in each county

# Make map of CA with dams per county
ggplot() +
  geom_sf(data = plants_per_county, 
          aes(fill = n), 
          size = 0.2, 
          color = "white") +
  scale_fill_continuous(low = "yellow", high = "red")
```

