---
title: "my_data_exploration"
author: "Oswaldo Felix"
date: "3/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(lubridate)
library(janitor)
library(tmap)
library(here)
library(sf)
```

This is just me checking out the data

### Here's EnviroScreen
```{r, fig.width = 10, fig.height = 6}
# Read in data set
env_scrn_df <- read_csv(here::here("data", "CalEnviroScreen.csv")) %>% 
  clean_names() %>% 
  rename(nearby_city = nearby_city_to_help_approximate_location_only,
         lon = longitude,
         lat = latitude,
         county = california_county) %>% 
  select(-contains("pctl"), -contains("percentile"))

# Convert to sf
env_scrn_sf <- st_as_sf(env_scrn_df, coords = c("lon", "lat"), crs = 4326)


# Make subset
env_scrn_sub <- env_scrn_sf %>%
  group_by(nearby_city) %>% 
  summarize(total_pop = sum(total_population),
            ozone = mean(ozone)) %>% 
  arrange(-total_pop) %>% 
  head(10)

# Make California base layer
ca <- read_sf(dsn = here::here("data", "states"),
              layer = "cb_2017_us_state_20m") %>% 
  dplyr::select(NAME) %>% 
  filter(NAME == "California") %>% 
  st_transform(crs = 4326)

# Let's look at the data
ozone_plot <- ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = env_scrn_sf, aes(color = ozone)) +
  scale_color_gradientn(colors = c("blue", "yellow")) +
  geom_sf_text(data = env_scrn_sub, aes(label = nearby_city),
               size = 3, fontface = "bold", 
               check_overlap = T) +
  theme_minimal()

ozone_plot

pop_plot <- ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = env_scrn_sf, 
          aes(color = ozone, size = total_population, 
              alpha = total_population)) +
  scale_color_gradientn(colors = c("blue", "yellow")) +
  scale_size_continuous(range = c(1,10)) +
  geom_sf_text(data = env_scrn_sub, aes(label = nearby_city),
               size = 3, fontface = "bold", 
               check_overlap = T) +
  guides(color = guide_colorbar("Ozone"), size = F, alpha = F) +
  theme_minimal()

pop_plot
```

### Here's Electricity
```{r}
# This data is messy
elec_raw <- read_csv(here::here("data", "ElectricityByCountyCal.csv"))

elec_res_df <- read_csv(here::here("data", "ElectricityByCountyCal.csv")) %>%
  filter(Sector == "Residential") %>% 
  select(-Sector, -"Total Usage") %>% 
  pivot_longer(-County, names_to = "year", values_to = "demand") %>% 
  clean_names() %>% 
  mutate(sector = "Residential")

elec_nres_df <- read_csv(here::here("data", "ElectricityByCountyCal.csv")) %>%
  filter(Sector == "Non-Residential") %>% 
  select(-Sector, -"Total Usage") %>% 
  pivot_longer(-County, names_to = "year", values_to = "demand") %>% 
  clean_names() %>% 
  mutate(sector = "Non-Residential")

elec_tot_df <- read_csv(here::here("data", "ElectricityByCountyCal.csv")) %>%
  filter(Sector == "Total") %>% 
  select(-Sector, -"Total Usage") %>% 
  pivot_longer(-County, names_to = "year", values_to = "demand") %>% 
  clean_names() %>% 
  mutate(sector = "Total")

elec_mid_df <- full_join(elec_nres_df, elec_res_df)

elec_df <- full_join(elec_mid_df, elec_tot_df) %>%
  mutate(year = as.numeric(year),
         county = str_to_title(county)) %>% 
  arrange(county) %>% 
  arrange(-year)

# Let's try to combine with spatial data

sp_sf <- env_scrn_sf %>%
  group_by(county) %>% 
  summarize(total_pop = sum(total_population),
            ozone = sum(ozone)) %>%
  select(county, total_pop, ozone)

elec_ca_sf <- sp_sf %>% 
  full_join(elec_df, by = "county")
```

```{r}
# Plotting

elec_ca_sub1 <- elec_ca_sf %>% 
  filter(year %in% c(1990, 2018)) %>% 
  filter(sector == "Residential")

ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = elec_ca_sub1, 
          aes(color = demand)) +
  scale_color_gradientn(colors = c("blue", "lightyellow", "red")) +
  theme_minimal() +
  facet_wrap(~year) +
  labs(title = "Residential energy demand")

elec_ca_sub2 <- elec_ca_sf %>% 
  filter(year %in% c(1990, 2018)) %>% 
  filter(sector == "Non-Residential")

ggplot() +
  geom_sf(data = ca) +
  geom_sf(data = elec_ca_sub2, 
          aes(color = demand)) +
  scale_color_gradientn(colors = c("blue", "lightyellow", "red")) +
  theme_minimal() +
  facet_wrap(~year) +
  labs(title = "Non-Residential energy demand")
```
 
```{r, fig.width = 10, fig.height = 6}
# More plotting
elec_ca_sub3 <- elec_ca_sf %>% 
  filter(sector == "Total") %>% 
  group_by(year) %>% 
  summarize(demand = sum(demand))

ggplot(data = elec_ca_sub3) +
  geom_line(aes(x = year, y = demand)) +
  geom_ribbon(fill = "lightyellow", alpha = 0.5,
              aes(x = year, ymin = 200000, 
                  ymax = demand)) +
  scale_y_continuous(limits = c(200000,300000)) +
  scale_x_continuous(breaks = c(1990, 1994, 1998, 2002, 
                                2006, 2010, 2014, 2018), 
                     labels = c(1990, 1994, 1998, 2002, 
                                2006, 2010, 2014, 2018)) +
  labs(title = "Net energy demand", 
       y = "Electricity [GWh]", x = "Year") +
  theme_minimal()
```
 

### Here's Plant data
```{r}
# ----------
# Read in data 
# ----------

gen_by_plant <- read_csv(here::here("data", "annual_generation_by_power_plant.csv"))

plant_info <- read_csv(here::here("data", "plant_info.csv"), 
                       skip = 12, col_names = TRUE)

metadata_df <- read_csv(here::here("data", "plant_metadata.csv"))

# --------
# Clean up data
# --------

tidy_gen_by_plant <- gen_by_plant %>% 
  clean_names() %>% 
  select(year, state, cec_plant_id, status, start_date, 
         retire_date, prime_mover_id, prime_mover_desc, 
         capacity, gross_m_wh, net_m_wh) %>% 
  rename("gross_mwh" = "gross_m_wh") %>% 
  rename("net_mwh" = "net_m_wh") %>% 
  # filter for just photovoltaics (this excludes solar thermal, wind, etc.)
  # but there are still plants that say the energy source is natural gas/other non-solar...
  filter(prime_mover_id == "PV")
  # for visuals, remember to filter out non-operational systems once they have a "retire date" so they still show up if a year is selected before retirement

tidy_plant_info <- plant_info %>% 
  clean_names() %>% 
  # we'll already have state in the other df
  select(-state)

# --------
# Join dataframes
# ---------

plants_location_join <- inner_join(tidy_plant_info, tidy_gen_by_plant, "cec_plant_id")
# note that there are a 19 entries wiht energy_source_category not equal to "SUN" but prime_mover_id equal to "PV"

```

